Pexels API request failed for query 'nature': 401 Client Error: Unauthorized for url: https://api.pexels.com/videos/search?query=nature&per_page=1&orientation=landscape
2025-09-27 16:08:11.014 Uncaught app execution
Traceback (most recent call last):
  File "C:\Users\digitalFORENSIK\AppData\Local\Programs\Python\Python313\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "C:\Users\digitalFORENSIK\AppData\Local\Programs\Python\Python313\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Easy-Text-To-Video-AI-main\Easy-Text-To-Video-AI-main\streamlit_main.py", line 33, in <module>
    final_path = get_output_media(AUDIO_FILE, timed_captions, video_segments, "pexels", VIDEO_FILE)
  File "E:\Easy-Text-To-Video-AI-main\Easy-Text-To-Video-AI-main\utility\video\video_merge.py", line 9, in get_output_media
    url = generate_video_url("nature")  # fallback
          ^^^^^^^^^^^^^^^^^^
NameError: name 'generate_video_url' is not defined
